// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: v1/user/user_service.proto

package user_repo

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Профиль пользователя
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // Уникальный идентификатор пользователя
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                          // Уникальный никнейм пользователя
	Bio           *string                `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`                              // Биография пользователя (опционально)
	AvatarUrl     *string                `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"` // URL аватара пользователя (опционально)
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`      // Время создания профиля (timestamp)
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`      // Время последнего обновления профиля (timestamp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_v1_user_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_v1_user_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UserProfile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserProfile) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Запрос на создание профиля
type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // ID пользователя
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                          // Никнейм пользователя
	Bio           *string                `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`                              // Биография пользователя (опционально)
	AvatarUrl     *string                `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"` // URL аватара пользователя (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_v1_user_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateProfileRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *CreateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// Запрос на обновление профиля
type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // ID пользователя
	Nickname      *string                `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`                    // Никнейм пользователя (опционально)
	Bio           *string                `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`                              // Биография пользователя (опционально)
	AvatarUrl     *string                `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"` // URL аватара пользователя (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_v1_user_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// Запрос на получение профиля по ID
type GetProfileByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDRequest) Reset() {
	*x = GetProfileByIDRequest{}
	mi := &file_v1_user_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDRequest) ProtoMessage() {}

func (x *GetProfileByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Запрос на получение профиля по никнейму
type GetProfileByNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"` // Никнейм пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByNicknameRequest) Reset() {
	*x = GetProfileByNicknameRequest{}
	mi := &file_v1_user_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByNicknameRequest) ProtoMessage() {}

func (x *GetProfileByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByNicknameRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileByNicknameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// Запрос на поиск по никнейму
type SearchByNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`  // Поисковый запрос
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Максимальное количество результатов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByNicknameRequest) Reset() {
	*x = SearchByNicknameRequest{}
	mi := &file_v1_user_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByNicknameRequest) ProtoMessage() {}

func (x *SearchByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByNicknameRequest.ProtoReflect.Descriptor instead.
func (*SearchByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *SearchByNicknameRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchByNicknameRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Ответ на поиск по никнейму
type SearchByNicknameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*UserProfile         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // Найденные профили
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByNicknameResponse) Reset() {
	*x = SearchByNicknameResponse{}
	mi := &file_v1_user_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByNicknameResponse) ProtoMessage() {}

func (x *SearchByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByNicknameResponse.ProtoReflect.Descriptor instead.
func (*SearchByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *SearchByNicknameResponse) GetResults() []*UserProfile {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_v1_user_user_service_proto protoreflect.FileDescriptor

const file_v1_user_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1av1/user/user_service.proto\x123github.com.BurMachine.Bigtech_microservices.v1.user\x1a\x1bbuf/validate/validate.proto\"\xd2\x01\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x15\n" +
	"\x03bio\x18\x03 \x01(\tH\x00R\x03bio\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x01R\tavatarUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAtB\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_url\"\xc5\x01\n" +
	"\x14CreateProfileRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x128\n" +
	"\bnickname\x18\x02 \x01(\tB\x1c\xbaH\x19r\x17\x10\x03\x18\x142\x11^[a-z0-9_]{3,20}$R\bnickname\x12\x15\n" +
	"\x03bio\x18\x03 \x01(\tH\x00R\x03bio\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x01R\tavatarUrl\x88\x01\x01B\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_url\"\xd7\x01\n" +
	"\x14UpdateProfileRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12=\n" +
	"\bnickname\x18\x02 \x01(\tB\x1c\xbaH\x19r\x17\x10\x03\x18\x142\x11^[a-z0-9_]{3,20}$H\x00R\bnickname\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\x03 \x01(\tH\x01R\x03bio\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x02R\tavatarUrl\x88\x01\x01B\v\n" +
	"\t_nicknameB\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_url\"1\n" +
	"\x15GetProfileByIDRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"W\n" +
	"\x1bGetProfileByNicknameRequest\x128\n" +
	"\bnickname\x18\x01 \x01(\tB\x1c\xbaH\x19r\x17\x10\x03\x18\x142\x11^[a-z0-9_]{3,20}$R\bnickname\"Y\n" +
	"\x17SearchByNicknameRequest\x12\x1d\n" +
	"\x05query\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05query\x12\x1f\n" +
	"\x05limit\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d \x00R\x05limit\"v\n" +
	"\x18SearchByNicknameResponse\x12Z\n" +
	"\aresults\x18\x01 \x03(\v2@.github.com.BurMachine.Bigtech_microservices.v1.user.UserProfileR\aresults2\xd5\x06\n" +
	"\vUserService\x12\x9e\x01\n" +
	"\rCreateProfile\x12I.github.com.BurMachine.Bigtech_microservices.v1.user.CreateProfileRequest\x1a@.github.com.BurMachine.Bigtech_microservices.v1.user.UserProfile\"\x00\x12\x9e\x01\n" +
	"\rUpdateProfile\x12I.github.com.BurMachine.Bigtech_microservices.v1.user.UpdateProfileRequest\x1a@.github.com.BurMachine.Bigtech_microservices.v1.user.UserProfile\"\x00\x12\xa0\x01\n" +
	"\x0eGetProfileByID\x12J.github.com.BurMachine.Bigtech_microservices.v1.user.GetProfileByIDRequest\x1a@.github.com.BurMachine.Bigtech_microservices.v1.user.UserProfile\"\x00\x12\xac\x01\n" +
	"\x14GetProfileByNickname\x12P.github.com.BurMachine.Bigtech_microservices.v1.user.GetProfileByNicknameRequest\x1a@.github.com.BurMachine.Bigtech_microservices.v1.user.UserProfile\"\x00\x12\xb1\x01\n" +
	"\x10SearchByNickname\x12L.github.com.BurMachine.Bigtech_microservices.v1.user.SearchByNicknameRequest\x1aM.github.com.BurMachine.Bigtech_microservices.v1.user.SearchByNicknameResponse\"\x00B\x89\x03\n" +
	"7com.github.com.BurMachine.Bigtech_microservices.v1.userB\x10UserServiceProtoP\x01ZLgithub.com/BurMachine/Bigtech_microservices/users/pkg/v1/user_repo;user_repo\xa2\x02\x06GCBBVU\xaa\x022Github.Com.BurMachine.BigtechMicroservices.V1.User\xca\x022Github\\Com\\BurMachine\\BigtechMicroservices\\V1\\User\xe2\x02>Github\\Com\\BurMachine\\BigtechMicroservices\\V1\\User\\GPBMetadata\xea\x027Github::Com::BurMachine::BigtechMicroservices::V1::Userb\x06proto3"

var (
	file_v1_user_user_service_proto_rawDescOnce sync.Once
	file_v1_user_user_service_proto_rawDescData []byte
)

func file_v1_user_user_service_proto_rawDescGZIP() []byte {
	file_v1_user_user_service_proto_rawDescOnce.Do(func() {
		file_v1_user_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_user_service_proto_rawDesc), len(file_v1_user_user_service_proto_rawDesc)))
	})
	return file_v1_user_user_service_proto_rawDescData
}

var file_v1_user_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_user_user_service_proto_goTypes = []any{
	(*UserProfile)(nil),                 // 0: github.com.BurMachine.Bigtech_microservices.v1.user.UserProfile
	(*CreateProfileRequest)(nil),        // 1: github.com.BurMachine.Bigtech_microservices.v1.user.CreateProfileRequest
	(*UpdateProfileRequest)(nil),        // 2: github.com.BurMachine.Bigtech_microservices.v1.user.UpdateProfileRequest
	(*GetProfileByIDRequest)(nil),       // 3: github.com.BurMachine.Bigtech_microservices.v1.user.GetProfileByIDRequest
	(*GetProfileByNicknameRequest)(nil), // 4: github.com.BurMachine.Bigtech_microservices.v1.user.GetProfileByNicknameRequest
	(*SearchByNicknameRequest)(nil),     // 5: github.com.BurMachine.Bigtech_microservices.v1.user.SearchByNicknameRequest
	(*SearchByNicknameResponse)(nil),    // 6: github.com.BurMachine.Bigtech_microservices.v1.user.SearchByNicknameResponse
}
var file_v1_user_user_service_proto_depIdxs = []int32{
	0, // 0: github.com.BurMachine.Bigtech_microservices.v1.user.SearchByNicknameResponse.results:type_name -> github.com.BurMachine.Bigtech_microservices.v1.user.UserProfile
	1, // 1: github.com.BurMachine.Bigtech_microservices.v1.user.UserService.CreateProfile:input_type -> github.com.BurMachine.Bigtech_microservices.v1.user.CreateProfileRequest
	2, // 2: github.com.BurMachine.Bigtech_microservices.v1.user.UserService.UpdateProfile:input_type -> github.com.BurMachine.Bigtech_microservices.v1.user.UpdateProfileRequest
	3, // 3: github.com.BurMachine.Bigtech_microservices.v1.user.UserService.GetProfileByID:input_type -> github.com.BurMachine.Bigtech_microservices.v1.user.GetProfileByIDRequest
	4, // 4: github.com.BurMachine.Bigtech_microservices.v1.user.UserService.GetProfileByNickname:input_type -> github.com.BurMachine.Bigtech_microservices.v1.user.GetProfileByNicknameRequest
	5, // 5: github.com.BurMachine.Bigtech_microservices.v1.user.UserService.SearchByNickname:input_type -> github.com.BurMachine.Bigtech_microservices.v1.user.SearchByNicknameRequest
	0, // 6: github.com.BurMachine.Bigtech_microservices.v1.user.UserService.CreateProfile:output_type -> github.com.BurMachine.Bigtech_microservices.v1.user.UserProfile
	0, // 7: github.com.BurMachine.Bigtech_microservices.v1.user.UserService.UpdateProfile:output_type -> github.com.BurMachine.Bigtech_microservices.v1.user.UserProfile
	0, // 8: github.com.BurMachine.Bigtech_microservices.v1.user.UserService.GetProfileByID:output_type -> github.com.BurMachine.Bigtech_microservices.v1.user.UserProfile
	0, // 9: github.com.BurMachine.Bigtech_microservices.v1.user.UserService.GetProfileByNickname:output_type -> github.com.BurMachine.Bigtech_microservices.v1.user.UserProfile
	6, // 10: github.com.BurMachine.Bigtech_microservices.v1.user.UserService.SearchByNickname:output_type -> github.com.BurMachine.Bigtech_microservices.v1.user.SearchByNicknameResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_user_user_service_proto_init() }
func file_v1_user_user_service_proto_init() {
	if File_v1_user_user_service_proto != nil {
		return
	}
	file_v1_user_user_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_user_user_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_user_user_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_user_service_proto_rawDesc), len(file_v1_user_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_user_service_proto_goTypes,
		DependencyIndexes: file_v1_user_user_service_proto_depIdxs,
		MessageInfos:      file_v1_user_user_service_proto_msgTypes,
	}.Build()
	File_v1_user_user_service_proto = out.File
	file_v1_user_user_service_proto_goTypes = nil
	file_v1_user_user_service_proto_depIdxs = nil
}
