version: '3.8'

networks:
  messenger:
    external: true

services:
  users:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users
    ports:
      - "8084:8084"
    environment:
      GRPC_PORT: 8084
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres_pass
      DB_NAME: users_db
      DB_SSLMODE: disable
      LOG_LEVEL: debug
    networks:
      - messenger
    restart: unless-stopped


