services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-service:latest
    container_name: user-service
    ports:
      - "8084:8084"
    environment:
      - ENV_VAR_EXAMPLE=value
    volumes:
      # Опционально: для логов (комментарий на отдельной строке)
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge