// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/BurMachine/Bigtech_microservices/users/internal/app/delivery/grpc"
	"github.com/BurMachine/Bigtech_microservices/users/internal/app/repositories/user"
	"github.com/BurMachine/Bigtech_microservices/users/internal/app/usecases/users"
	"github.com/google/wire"
)

// Injectors from provider.go:

// Wire — генерируемая функция (не пиши тело!)
func Wire(dbDSN string) (*user_grpc.Service, error) {
	db, err := NewDB(dbDSN)
	if err != nil {
		return nil, err
	}
	userRepository := user_repo.New(db)
	usecases := users.NewUsecases(userRepository)
	service, err := user_grpc.NewServer(usecases)
	if err != nil {
		return nil, err
	}
	return service, nil
}

// provider.go:

// NewDB — провайдер для DB (теперь здесь, чтобы импорт использовался)
func NewDB(dbDSN string) (*sql.DB, error) {

	return &sql.DB{}, nil
}

// ProviderSet — сет зависимостей
var ProviderSet = wire.NewSet(
	NewDB, user_repo.New, users.NewUsecases, user_grpc.NewServer,
)
