// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/BurMachine/Bigtech_microservices/users/internal/app/delivery/grpc"
	"github.com/BurMachine/Bigtech_microservices/users/internal/app/repositories/user"
	"github.com/BurMachine/Bigtech_microservices/users/internal/app/usecases/users"
	"github.com/BurMachine/Bigtech_microservices/users/pkg/postgres"
	"github.com/BurMachine/Bigtech_microservices/users/pkg/postgres/transaction_manager"
	"github.com/google/wire"
)

// Injectors from provider.go:

// Wire — генерируемая функция
func Wire(dbDSN string) (*user_grpc.Service, error) {
	context := ProvideContext()
	v := ProvideConnectionPoolOptions()
	connection, err := postgres.NewConnectionPool(context, dbDSN, v...)
	if err != nil {
		return nil, err
	}
	transactionManager := transaction_manager.New(connection)
	queryEngineProvider := ProvideQueryEngineProvider(transactionManager)
	userRepository := users_repo.NewRepository(queryEngineProvider)
	usecases := users.NewUsecases(userRepository, transactionManager)
	service, err := user_grpc.NewServer(usecases)
	if err != nil {
		return nil, err
	}
	return service, nil
}

// provider.go:

// Провайдер для контекста
func ProvideContext() context.Context {
	return context.Background()
}

// Провайдер для опций пула соединений (пустой слайс)
func ProvideConnectionPoolOptions() []postgres.ConnectionPoolOption {
	return []postgres.ConnectionPoolOption{}
}

// Провайдер для QueryEngineProvider
func ProvideQueryEngineProvider(tm *transaction_manager.TransactionManager) postgres.QueryEngineProvider {
	return tm
}

// ProviderSet — сет зависимостей
var ProviderSet = wire.NewSet(
	ProvideContext,
	ProvideConnectionPoolOptions,
	ProvideQueryEngineProvider, postgres.NewConnectionPool, transaction_manager.New, wire.Bind(new(users.TransactionManager), new(*transaction_manager.TransactionManager)), users_repo.NewRepository, users.NewUsecases, user_grpc.NewServer,
)
