// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: v1/chat/chat_service.proto

package chat

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a direct chat.
type CreateDirectChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the participant (required, must be a valid user ID).
	ParticipantId string `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatRequest) Reset() {
	*x = CreateDirectChatRequest{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatRequest) ProtoMessage() {}

func (x *CreateDirectChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectChatRequest) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDirectChatRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

// Response for creating a direct chat.
type CreateDirectChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the created chat.
	ChatId        string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatResponse) Reset() {
	*x = CreateDirectChatResponse{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatResponse) ProtoMessage() {}

func (x *CreateDirectChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectChatResponse) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDirectChatResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// Request to get a chat.
type GetChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the chat (required, must be a valid chat ID).
	ChatId        string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// Chat entity.
type Chat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the chat (required).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// List of participant user IDs (at least 2 for direct chats).
	ParticipantIds []string `protobuf:"bytes,2,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{3}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

// Request to list user chats.
type ListUserChatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the user (required, must be a valid user ID).
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsRequest) Reset() {
	*x = ListUserChatsRequest{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsRequest) ProtoMessage() {}

func (x *ListUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserChatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response for listing user chats.
type ListUserChatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of chats the user is in.
	Chats         []*Chat `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsResponse) Reset() {
	*x = ListUserChatsResponse{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsResponse) ProtoMessage() {}

func (x *ListUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

// Request to list chat members.
type ListChatMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the chat (required, must be a valid chat ID).
	ChatId        string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMembersRequest) Reset() {
	*x = ListChatMembersRequest{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMembersRequest) ProtoMessage() {}

func (x *ListChatMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMembersRequest.ProtoReflect.Descriptor instead.
func (*ListChatMembersRequest) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListChatMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// Response for listing chat members.
type ListChatMembersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of user IDs in the chat.
	UserIds       []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMembersResponse) Reset() {
	*x = ListChatMembersResponse{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMembersResponse) ProtoMessage() {}

func (x *ListChatMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMembersResponse.ProtoReflect.Descriptor instead.
func (*ListChatMembersResponse) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListChatMembersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// Request to send a message.
type SendMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the chat (required, must be a valid chat ID).
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Text of the message (required, non-empty string).
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Message entity.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID of the message (generated).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the chat.
	ChatId string `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// ID of the sender user.
	SenderId string `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Text content of the message.
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// Unix timestamp in milliseconds when the message was sent.
	TimestampUnixMs int64 `protobuf:"varint,5,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// Request to list messages.
type ListMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the chat (required, must be a valid chat ID).
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Limit on the number of messages to return (required, positive integer).
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Optional pagination cursor for the next page.
	Cursor        *string `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

// Response for listing messages.
type ListMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of messages in descending order (newest first).
	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// Optional next pagination cursor.
	NextCursor    *string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

// Request for streaming messages.
type StreamMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the chat (required, must be a valid chat ID).
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Optional starting Unix timestamp in milliseconds.
	SinceUnixMs   *int64 `protobuf:"varint,2,opt,name=since_unix_ms,json=sinceUnixMs,proto3,oneof" json:"since_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_v1_chat_chat_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_chat_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v1_chat_chat_service_proto_rawDescGZIP(), []int{12}
}

func (x *StreamMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *StreamMessagesRequest) GetSinceUnixMs() int64 {
	if x != nil && x.SinceUnixMs != nil {
		return *x.SinceUnixMs
	}
	return 0
}

var File_v1_chat_chat_service_proto protoreflect.FileDescriptor

const file_v1_chat_chat_service_proto_rawDesc = "" +
	"\n" +
	"\x1av1/chat/chat_service.proto\x12\x1dBigtech_microservices.v1.chat\x1a\x1bbuf/validate/validate.proto\"J\n" +
	"\x17CreateDirectChatRequest\x12/\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rparticipantId\"=\n" +
	"\x18CreateDirectChatResponse\x12!\n" +
	"\achat_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06chatId\"3\n" +
	"\x0eGetChatRequest\x12!\n" +
	"\achat_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06chatId\"Z\n" +
	"\x04Chat\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x128\n" +
	"\x0fparticipant_ids\x18\x02 \x03(\tB\x0f\xbaH\f\x92\x01\t\b\x02\"\x05r\x03\xb0\x01\x01R\x0eparticipantIds\"9\n" +
	"\x14ListUserChatsRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\"R\n" +
	"\x15ListUserChatsResponse\x129\n" +
	"\x05chats\x18\x01 \x03(\v2#.Bigtech_microservices.v1.chat.ChatR\x05chats\";\n" +
	"\x16ListChatMembersRequest\x12!\n" +
	"\achat_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06chatId\"C\n" +
	"\x17ListChatMembersResponse\x12(\n" +
	"\buser_ids\x18\x01 \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\auserIds\"T\n" +
	"\x12SendMessageRequest\x12!\n" +
	"\achat_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06chatId\x12\x1b\n" +
	"\x04text\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04text\"\xbf\x01\n" +
	"\aMessage\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12!\n" +
	"\achat_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06chatId\x12%\n" +
	"\tsender_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bsenderId\x12\x1b\n" +
	"\x04text\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04text\x123\n" +
	"\x11timestamp_unix_ms\x18\x05 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\x0ftimestampUnixMs\"\x7f\n" +
	"\x13ListMessagesRequest\x12!\n" +
	"\achat_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06chatId\x12\x1d\n" +
	"\x05limit\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\x90\x01\n" +
	"\x14ListMessagesResponse\x12B\n" +
	"\bmessages\x18\x01 \x03(\v2&.Bigtech_microservices.v1.chat.MessageR\bmessages\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"~\n" +
	"\x15StreamMessagesRequest\x12!\n" +
	"\achat_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06chatId\x120\n" +
	"\rsince_unix_ms\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02(\x00H\x00R\vsinceUnixMs\x88\x01\x01B\x10\n" +
	"\x0e_since_unix_ms2\xc6\x06\n" +
	"\vChatService\x12\x83\x01\n" +
	"\x10CreateDirectChat\x126.Bigtech_microservices.v1.chat.CreateDirectChatRequest\x1a7.Bigtech_microservices.v1.chat.CreateDirectChatResponse\x12]\n" +
	"\aGetChat\x12-.Bigtech_microservices.v1.chat.GetChatRequest\x1a#.Bigtech_microservices.v1.chat.Chat\x12z\n" +
	"\rListUserChats\x123.Bigtech_microservices.v1.chat.ListUserChatsRequest\x1a4.Bigtech_microservices.v1.chat.ListUserChatsResponse\x12\x80\x01\n" +
	"\x0fListChatMembers\x125.Bigtech_microservices.v1.chat.ListChatMembersRequest\x1a6.Bigtech_microservices.v1.chat.ListChatMembersResponse\x12h\n" +
	"\vSendMessage\x121.Bigtech_microservices.v1.chat.SendMessageRequest\x1a&.Bigtech_microservices.v1.chat.Message\x12w\n" +
	"\fListMessages\x122.Bigtech_microservices.v1.chat.ListMessagesRequest\x1a3.Bigtech_microservices.v1.chat.ListMessagesResponse\x12p\n" +
	"\x0eStreamMessages\x124.Bigtech_microservices.v1.chat.StreamMessagesRequest\x1a&.Bigtech_microservices.v1.chat.Message0\x01B\xdd\x01\n" +
	"!com.Bigtech_microservices.v1.chatB\x10ChatServiceProtoP\x01Z\x14pkg/api/v1/chat;chat\xa2\x02\x03BVC\xaa\x02\x1cBigtechMicroservices.V1.Chat\xca\x02\x1cBigtechMicroservices\\V1\\Chat\xe2\x02(BigtechMicroservices\\V1\\Chat\\GPBMetadata\xea\x02\x1eBigtechMicroservices::V1::Chatb\x06proto3"

var (
	file_v1_chat_chat_service_proto_rawDescOnce sync.Once
	file_v1_chat_chat_service_proto_rawDescData []byte
)

func file_v1_chat_chat_service_proto_rawDescGZIP() []byte {
	file_v1_chat_chat_service_proto_rawDescOnce.Do(func() {
		file_v1_chat_chat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_chat_chat_service_proto_rawDesc), len(file_v1_chat_chat_service_proto_rawDesc)))
	})
	return file_v1_chat_chat_service_proto_rawDescData
}

var file_v1_chat_chat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_chat_chat_service_proto_goTypes = []any{
	(*CreateDirectChatRequest)(nil),  // 0: Bigtech_microservices.v1.chat.CreateDirectChatRequest
	(*CreateDirectChatResponse)(nil), // 1: Bigtech_microservices.v1.chat.CreateDirectChatResponse
	(*GetChatRequest)(nil),           // 2: Bigtech_microservices.v1.chat.GetChatRequest
	(*Chat)(nil),                     // 3: Bigtech_microservices.v1.chat.Chat
	(*ListUserChatsRequest)(nil),     // 4: Bigtech_microservices.v1.chat.ListUserChatsRequest
	(*ListUserChatsResponse)(nil),    // 5: Bigtech_microservices.v1.chat.ListUserChatsResponse
	(*ListChatMembersRequest)(nil),   // 6: Bigtech_microservices.v1.chat.ListChatMembersRequest
	(*ListChatMembersResponse)(nil),  // 7: Bigtech_microservices.v1.chat.ListChatMembersResponse
	(*SendMessageRequest)(nil),       // 8: Bigtech_microservices.v1.chat.SendMessageRequest
	(*Message)(nil),                  // 9: Bigtech_microservices.v1.chat.Message
	(*ListMessagesRequest)(nil),      // 10: Bigtech_microservices.v1.chat.ListMessagesRequest
	(*ListMessagesResponse)(nil),     // 11: Bigtech_microservices.v1.chat.ListMessagesResponse
	(*StreamMessagesRequest)(nil),    // 12: Bigtech_microservices.v1.chat.StreamMessagesRequest
}
var file_v1_chat_chat_service_proto_depIdxs = []int32{
	3,  // 0: Bigtech_microservices.v1.chat.ListUserChatsResponse.chats:type_name -> Bigtech_microservices.v1.chat.Chat
	9,  // 1: Bigtech_microservices.v1.chat.ListMessagesResponse.messages:type_name -> Bigtech_microservices.v1.chat.Message
	0,  // 2: Bigtech_microservices.v1.chat.ChatService.CreateDirectChat:input_type -> Bigtech_microservices.v1.chat.CreateDirectChatRequest
	2,  // 3: Bigtech_microservices.v1.chat.ChatService.GetChat:input_type -> Bigtech_microservices.v1.chat.GetChatRequest
	4,  // 4: Bigtech_microservices.v1.chat.ChatService.ListUserChats:input_type -> Bigtech_microservices.v1.chat.ListUserChatsRequest
	6,  // 5: Bigtech_microservices.v1.chat.ChatService.ListChatMembers:input_type -> Bigtech_microservices.v1.chat.ListChatMembersRequest
	8,  // 6: Bigtech_microservices.v1.chat.ChatService.SendMessage:input_type -> Bigtech_microservices.v1.chat.SendMessageRequest
	10, // 7: Bigtech_microservices.v1.chat.ChatService.ListMessages:input_type -> Bigtech_microservices.v1.chat.ListMessagesRequest
	12, // 8: Bigtech_microservices.v1.chat.ChatService.StreamMessages:input_type -> Bigtech_microservices.v1.chat.StreamMessagesRequest
	1,  // 9: Bigtech_microservices.v1.chat.ChatService.CreateDirectChat:output_type -> Bigtech_microservices.v1.chat.CreateDirectChatResponse
	3,  // 10: Bigtech_microservices.v1.chat.ChatService.GetChat:output_type -> Bigtech_microservices.v1.chat.Chat
	5,  // 11: Bigtech_microservices.v1.chat.ChatService.ListUserChats:output_type -> Bigtech_microservices.v1.chat.ListUserChatsResponse
	7,  // 12: Bigtech_microservices.v1.chat.ChatService.ListChatMembers:output_type -> Bigtech_microservices.v1.chat.ListChatMembersResponse
	9,  // 13: Bigtech_microservices.v1.chat.ChatService.SendMessage:output_type -> Bigtech_microservices.v1.chat.Message
	11, // 14: Bigtech_microservices.v1.chat.ChatService.ListMessages:output_type -> Bigtech_microservices.v1.chat.ListMessagesResponse
	9,  // 15: Bigtech_microservices.v1.chat.ChatService.StreamMessages:output_type -> Bigtech_microservices.v1.chat.Message
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_v1_chat_chat_service_proto_init() }
func file_v1_chat_chat_service_proto_init() {
	if File_v1_chat_chat_service_proto != nil {
		return
	}
	file_v1_chat_chat_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_v1_chat_chat_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_v1_chat_chat_service_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_chat_chat_service_proto_rawDesc), len(file_v1_chat_chat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_chat_chat_service_proto_goTypes,
		DependencyIndexes: file_v1_chat_chat_service_proto_depIdxs,
		MessageInfos:      file_v1_chat_chat_service_proto_msgTypes,
	}.Build()
	File_v1_chat_chat_service_proto = out.File
	file_v1_chat_chat_service_proto_goTypes = nil
	file_v1_chat_chat_service_proto_depIdxs = nil
}
